### ISSUE TITLE
--update problem

### ISSUE THREAD

**Issue by jarlave** [jtara1/RedditImageGrab#3]
Hey,

your fork is really nice, like it, but if I try to use --update, it always says:

No more ITEMS for wallpapers new
Downloaded from 0 reddit submissions
(Processed 0, Skipped 0, Errors 0)

it looks like it uses the last-id in history and watch at the end of this subreddit, but the newest are on top.

If I delete the history file it downloads the newest, but it doesn't stop if a file is already downloaded.

readme: --update              Run until you encounter a file already downloaded.

**Comment by jtara1** [comment]
Ok I fixed this with my latest commit.

I haven't really used or thought about --update arg until now. Instead of deleting your ._history.txt file everytime you could pass --restart arg to force it to begin downloading from beginning of subreddit.

Do you think it'd be a good idea to set --restart arg to True any time --update is passed? I suppose this would make more sense. I suppose --update arg intended use is to get the newest images since we last downloaded.

**Comment by jarlave** [comment]
Tested an works perfectly, and I think it is a good idea to set --restart to True if --update is passed.
The last-id get grabbed anyway without --update if someone want continue downloading at the last-id point.
